# Generated by Django 4.1 on 2023-11-19 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('nasa', '0002_alter_sliderobject_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderobject',
            options={'ordering': ['my_order'], 'verbose_name': 'Объекты слайдера'},
        ),
        migrations.AddField(
            model_name='sliderobject',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sliderobject',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='sliderobject',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Имя фотографии'),
        ),
    ]
